api/urls.py
from django.urls import path
from . import views
# from django.views.decorators.csrf import csrf_exempt

app_name = 'api'

urlpatterns = [
    path('v1/vote/', views.CreateVoteView.as_view(), name='create_vote'),
]

base/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'base'

urlpatterns = [
    # path('', views.TopView.as_view(), name='top'),
    path('', views.TopicListView.as_view(), name='top'),
    path('terms/', TemplateView.as_view(template_name='base/terms.html'), name='terms'),
    path('policy/', TemplateView.as_view(template_name='base/policy.html'), name='policy'),
    path('about/', TemplateView.as_view(template_name='base/about.html'), name='about'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from base.sitemaps import BaseSitemap
from thread.sitemaps import TopicSitemap, CategorySitemap

sitemaps = {
    'topic': TopicSitemap,
    'category': CategorySitemap,
    'base': BaseSitemap,
}


urlpatterns = [
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('', include('base.urls')),
    path('thread/', include('thread.urls')),
    path('api/', include('api.urls')),
    path('search/', include('search.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

thread/urls.py
from django.urls import path

from . import views
app_name = 'thread'

urlpatterns = [
    # path('<int:pk>/', views.TopicDetailView.as_view(), name='topic'),
    path('create_topic/', views.TopicCreateView.as_view(), name='create_topic'),
    path('<int:pk>/', views.TopicAndCommentView.as_view(), name='topic'),
    path('category/<str:url_code>/', views.CategoryView.as_view(), name='category'),
]

thread/forms.py
from django import forms
from .models import Topic, Comment, Category


class TopicModelFrom(forms.ModelForm):
    # ゲストユーザ用入力項目
    user_name = forms.CharField(
        label='ゲストユーザ名',
        required=True,
    )

    class Meta:
        model = Topic
        fields = [
            'title',
            # 'user_name',
            'category',
            'message',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'hoge'}),
            # 'user_name' : forms.TextInput(attrs={'value': '名無し'}),

        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = '選択して下さい'
        self.fields['user_name'].widget.attrs['value'] = '匿名'

    def save(self, commit=True):
        topic = super().save(commit=False)
        topic.user_name = self.cleaned_data['user_name']
        if commit:
            topic.save()
        return topic


class LoginedUserTopicModelFrom(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'title',
            'category',
            'message',
        ]
        widgets = {
            'title': forms.TextInput(attrs={'class': 'hoge'}),
        }

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = '選択して下さい'

    def save(self, user, commit=True, **kwargs):
        topic = super().save(commit=False)
        topic.user = user
        topic.user_name = user.username
        if commit:
            topic.save()
        return topic


class CommentModelForm(forms.ModelForm):
    # ゲストユーザ用入力項目
    user_name = forms.CharField(
        label='ゲストユーザ名',
        required=True,
    )

    class Meta:
        model = Comment
        fields = [
            # 'user_name',
            'message',
            'image',
        ]

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['user_name'].widget.attrs['value'] = '名無し'

    def save_with_topic(self, topic_id, commit=True, **kwargs):
        comment = self.save(commit=False)
        comment.topic = Topic.objects.get(id=topic_id)
        comment.no = Comment.objects.filter(topic_id=topic_id).count() + 1
        comment.user_name = self.cleaned_data['user_name']
        if commit:
            comment.save()
        return comment


class LoginedUserCommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'message',
            'image',
        ]

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)

    def save_with_topic(self, topic_id, user, commit=True, **kwargs):
        comment = self.save(commit=False)
        comment.topic = Topic.objects.get(id=topic_id)
        comment.no = Comment.objects.filter(topic_id=topic_id).count() + 1
        print(user.is_authenticated, user, user.username)
        comment.user = user
        comment.user_name = user.username
        if commit:
            comment.save()
        return comment


class TopicCreateForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            'title',
            'user_name',
            'category',
            'message',
        ]

    def __init__(self, *args, **kwargs):
        # kwargs.setdefault('label_suffix', '')
        super().__init__(*args, **kwargs)
        self.fields['category'].empty_label = '選択して下さい'
        self.fields['user_name'].widget.attrs['value'] = '匿名'
        self.fields['title'].widget.attrs['class'] = 'huga'


# class CommentModelForm(forms.ModelForm):
#     class Meta:
#         model = Comment
#         fields = [
#             'user_name',
#             'message',
#             'image',
#         ]
#
#     def __init__(self, *args, **kwargs):
#         kwargs.setdefault('label_suffix', '')
#         super().__init__(*args, **kwargs)
#         self.fields['user_name'].widget.attrs['value'] = '名無し'
#
#     def save_with_topic(self, topic_id, commit=True):
#         comment = self.save(commit=False)
#         comment.topic = Topic.objects.get(id=topic_id)
#         comment.no = Comment.objects.filter(topic_id=topic_id).count() + 1
#         if commit:
#             comment.save()
#         return comment


class TopicForm(forms.Form):
    title = forms.CharField(
        label='タイトル',
        max_length=255,
        required=True,
    )
    user_name = forms.CharField(
        label='お名前',
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={'value': '匿名'}),
    )
    category = forms.ModelChoiceField(
        label='カテゴリー',
        queryset=Category.objects.all(),
        required=True,
        empty_label='選択して下さい',
    )
    message = forms.CharField(
        label='本文',
        widget=forms.Textarea,
        required=True,
    )

    def __init__(self, *args, **kwargs):
        kwargs.setdefault('label_suffix', '：')
        super().__init__(*args, **kwargs)

thread/views.py
from django.core.mail import send_mail, EmailMessage
from django.db.models import Count
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import (
    CreateView, FormView, DetailView, TemplateView, ListView)
from django.urls import reverse_lazy

from . forms import (
    TopicModelFrom, TopicForm, CommentModelForm,
    LoginedUserTopicModelFrom, LoginedUserCommentModelForm
)
from . models import Topic, Category, Comment, Vote


class TopicDetailView(DetailView):
    template_name = 'thread/detail_topic.html'
    model = Topic
    context_object_name = 'topic'


class TopicCreateView(CreateView):
    template_name = 'thread/create_topic.html'
    form_class = LoginedUserTopicModelFrom
    model = Topic
    success_url = reverse_lazy('base:top')

    def get_form_class(self):
        """ ログイン状態によってフォームを動的に変更する
        """
        if self.request.user.is_authenticated:
            return LoginedUserTopicModelFrom
        else:
            return TopicModelFrom

    def form_valid(self, form):
        ctx = {'form': form}
        if self.request.POST.get('next', '') == 'confirm':
            ctx['category'] = form.cleaned_data['category']
            return render(self.request, 'thread/confirm_topic.html', ctx)
        if self.request.POST.get('next', '') == 'back':
            return render(self.request, 'thread/create_topic.html', ctx)
        if self.request.POST.get('next', '') == 'create':
            form.save(self.request.user)
            # メール送信処理
            # send_mail(
            #     subject='トピック作成: ' + form.cleaned_data['title'],
            #     message='トピックが生成されました',
            #     from_email='hogehoge@example.com',
            #     recipient_list = [
            #         'admin@example.com',
            #     ]
            # )
            # return super().form_valid(form)
            return redirect(self.success_url)
        else:
            # 正常動作ではここは通らない。エラーページへの遷移でも良い
            return redirect(reverse_lazy('base:top'))


class TopicAndCommentView(FormView):
    template_name = 'thread/detail_topic.html'
    form_class = LoginedUserCommentModelForm

    def get_form_class(self):
        """ ログイン状態によってフォームを動的に変更する
        """
        if self.request.user.is_authenticated:
            return LoginedUserCommentModelForm
        else:
            return CommentModelForm

    def form_valid(self, form):
        # comment = form.save(commit=False)  # 保存せずオブジェクト生成する
        # comment.topic = Topic.objects.get(id=self.kwargs['pk'])
        # comment.no = Comment.objects.get(topic=self.kwargs['pk']).count() + 1
        # comment.save()

        # Comment.objects.create_comment(
        #       user_name=form.cleaned_data['user_name'],
        #       message=form.cleaned_data['message'],
        #       topic_id=self.kwargs['pk'],
        #       image=form.cleaned_data['image']
        #   )
        kwargs = {}
        if self.request.user.is_authenticated:
            kwargs['user'] = self.request.user
        # コメント保存のためsave_with_topicメソッドを呼ぶ
        form.save_with_topic(self.kwargs.get('pk'), **kwargs)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('thread:topic', kwargs={'pk': self.kwargs['pk']})

    def get_context_data(self):
        ctx = super().get_context_data()
        ctx['topic'] = Topic.objects.get(id=self.kwargs['pk'])
        # ctx['comment_list'] = Comment.objects.filter(
        #          topic_id=self.kwargs['pk']).order_by('no')
        ctx['comment_list'] = Comment.objects.filter(
            topic_id=self.kwargs['pk']).annotate(vote_count=Count('vote')).order_by('no')
        return ctx


class CategoryView(ListView):
    template_name = 'thread/category.html'
    context_object_name = 'topic_list'
    paginate_by = 5
    page_kwarg = 'p'

    def get_queryset(self):
        return Topic.objects.filter(category__url_code=self.kwargs['url_code'])

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx['category'] = get_object_or_404(Category, url_code=self.kwargs['url_code'])
        return ctx


class TopicCreateViewBySession(FormView):
    """セッションを使用したトピック作成
    """
    template_name = 'thread/create_topic.html'
    form_class = TopicForm

    def post(self, request, *args, **kwargs):
        ctx = {}
        if request.POST.get('next', '') == 'back':
            if 'input_data' in self.request.session:
                input_data = self.request.session['input_data']
                form = TopicForm(input_data)
                ctx['form'] = form
            return render(request, self.template_name, ctx)
        elif request.POST.get('next', '') == 'create':
            if 'input_data' in self.request.session:
                Topic.objects.create_topic(
                    title=request.session['input_data']['title'],
                    user_name=request.session['input_data']['user_name'],
                    category_id=request.session['input_data']['category'],
                    message=request.session['input_data']['message'],
                )
                # メールの送信処理は省略
                response = redirect(reverse_lazy('base:top'))
                response.set_cookie('categ_id', request.session['input_data']['category'])
                # セッションに保管した情報の削除
                request.session.pop('input_data')
                return response
        elif request.POST.get('next', '') == 'confirm':
            form = TopicForm(request.POST)
            if form.is_valid():
                ctx = {'form': form}
                # セッションにデータを保存
                input_data = {
                    'title': form.cleaned_data['title'],
                    'user_name': form.cleaned_data['user_name'],
                    'category': form.cleaned_data['category'].id,
                    'message': form.cleaned_data['message'],
                }
                request.session['input_data'] = input_data
                ctx['category'] = form.cleaned_data['category']
                return render(request, 'thread/confirm_topic.html', ctx)
            else:
                return render(request, self.template_name, {'form': form})

    def get_context_data(self):
        ctx = super().get_context_data()
        if 'categ_id' in self.request.COOKIES:
            form = ctx['form']
            form['category'].field.initial = self.request.COOKIES['categ_id']
            ctx['form'] = form
        return ctx
        

# def topic_create(request):
#     template_name = 'thread/create_topic.html'
#     ctx = {}
#     if request.method == 'GET':
#         # form = TopicForm()
#         # ctx['form'] = form
#         ctx['form'] = TopicCreateForm()
#         return render(request, template_name, ctx)
#
#     if request.method == 'POST':
#         topic_form = TopicCreateForm(request.POST)
#         if topic_form.is_valid():
#             topic_form.save()
#             # topic = Topic()
#             # cleaned_data = topic_form.cleaned_data
#             # topic.title = cleaned_data['title']
#             # topic.message = cleaned_data['message']
#             # topic.user_name = cleaned_data['user_name']
#             # topic.category = cleaned_data['category']
#             # topic.save()
#             return redirect(reverse_lazy('base:top'))
#         else:
#             ctx['form'] = topic_form
#             return render(request, template_name, ctx)

templates/thread/category.html
{% extends 'base/base.html' %}
{% block title %}{{category.name}} - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <!-- <a class="section">TOP</a> -->
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">{{category.name}}</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>{{category.name}}</h3></div>
                {% include 'base/pagination.html' %}
                <div class="ui divided items">
                    {% if topic_list %}
                    {% for topic in topic_list %}
                    <div class="item">
                        <div class="content">
                            <div class="header">
                                <a href="{% url 'thread:topic' pk=topic.id %}"><h4>{{topic.title}}</h4></a>
                            </div>
                            <div class="meta">
                                <span class="name">{{topic.user_name}}</span>
                                <span class="date">{{topic.created}}</span>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                    <div class="ui warning message">トピックが存在しません</div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/thread/confirm_topic.html
{% extends 'base/base.html' %}
{% block title %}トピック作成 - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">トピック作成</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>トピック作成</h3></div>
                <p>内容を確認してください</p>
                <table  class="ui celled table table table-hover" >
                    <tr><td>タイトル</td><td>{{form.title.value}}</td></tr>
                    {% if user.is_authenticated %}
                    <tr><td>お名前</td><td>{{user.username}}</td></tr>
                    {% else %}
                    <tr><td>ゲスト名</td><td>{{form.cleaned_data.user_name}}</td></tr>
                    {% endif %}
                    <tr><td>カテゴリー</td><td>{{form.cleaned_data.category}}</td></tr>
                    <tr><td>本文</td><td><pre>{{form.message.value}}</pre></td></tr>
                </table>
                <form class="ui form" action="{% url 'thread:create_topic' %}" method="POST">
                    {% csrf_token %}
                    {% for field in form %}
                        {{field.as_hidden}}
                    {% endfor %}
                    <button class="ui button grey" type="submit" name="next" value="back">戻る</button>
                    <button class="ui button orange" type="submit" name="next" value="create">作成</button>
                </form>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/thread/create_topic.html
{% extends 'base/base.html' %}
{% block title %}トピック作成 - {{ block.super }}{% endblock %}
{% block content %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a class="active section">トピック作成</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>トピック作成</h3></div>
                {% if not user.is_authenticated %}
                <div class="ui warning message">
                    <p>ゲストユーザーでトピック作成しますか？ログインする場合は以下のボタンでログインして下さい。</p>
                    <a class="ui button orange" href="/accounts/login?next=/thread/create_topic/">ログイン</a>
                </div>
                {% endif %}
                <form class="ui form" action="{% url 'thread:create_topic' %}" method="POST">
                    {% csrf_token %}
                    <!-- {{form.as_p}} -->
                    {% for field in form %}
                    <div class="field">{{field.label_tag}}{{field}}</div>
                        {% for error in field.errors%}
                        <p style="color: red;">{{error}}</p>
                        {% endfor%}
                    {% endfor %}
                    <button type="submit" class="ui button" name="next" value="confirm">作成</button>
                </form>
            </div>
        </div>
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}

templates/thread/detail_topic.html
{% extends 'base/base.html' %}
{% block title %}トピック作成 - {{ block.super }}{% endblock %}
{% block content %}
{% load threadfilters %}
{% load static %}
<div class="ui grid stackable">
    <div class="eleven wide column">
        <div class="ui breadcrumb">
            <a href="{% url 'base:top' %}" class="section">TOP</a>
            <i class="right angle icon divider"></i>
            <a href="{% url 'thread:category' url_code=topic.category.url_code %}" class="section">{{topic.category.name}}</a>
            <i class="right angle icon divider"></i>
            <a class="active section">{{topic.title}}</a>
        </div>
        <div class="ui segment">
            <div class="content">
                <div class="header"><h3>{{topic.title}}</h3></div>
                <p>{% if topic.user %}{{topic.user}}{% else %}{{topic.user_name}}{% endif %} - {{topic.created}}</p>
                <div class="ui segment">
                    <p><pre>{{topic.message}}</pre></p>
                </div>
            </div>
        </div>
        <!--コメント表示-->
        <div class="ui segment">
            {% if comment_list %}
            {% for comment in comment_list %}
            <div class="ui segment secondary">
                <p>{{comment.no}}. {% if comment.user %}{{comment.user.username}}{% else %}{{comment.user_name}}{% endif %}
                <br>{{comment.created}}</p>
                {% if comment.pub_flg %}
                <p>{{comment.message | comment_filter | safe}}</p>
                    {% if comment.image %}
                    <a href="{{comment.image.url}}" target="_blank" rel="noopener noreferrer"><img src="{{comment.image.url}}" width=200px></a>
                    {% endif %}
                <div class="ui right aligned vertical segment">
                    <div class="vote_button" style="cursor: pointer;"
                        data-comment-id="{{comment.id}}" data-count="{{comment.vote_count}}">
                        <i class="heart outline icon"></i>
                        <span class="vote_counter">
                            {% if comment.vote_count > 0 %}{{comment.vote_count}}{% endif %}
                        </span>
                    </div>
                </div>
                {% else %}
                <p style="color: grey">コメントは非表示とされました</p>
                {% endif %}
            </div>
            {% endfor %}
            {% else %}
            <div class="ui warning message"><p>まだコメントはありません</p></div>
            {% endif %}
        </div>
        <!--//コメント表示-->
        <!--コメント投稿-->
        <h4>コメント投稿</h4>
        {% if not user.is_authenticated %}
        <div class="ui warning message">
            <p>ゲストユーザーで投稿しますか？ログインする場合は以下のボタンでログインして下さい。</p>
            <a class="ui button orange" href="/accounts/login?next=/thread/{{topic.id}}/">ログイン</a>
        </div>
        {% endif %}
        <div class="ui segment">
            <form class="ui form" action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <button class="ui button orange" type="submit">コメント投稿</button>
            </form>
        </div>
        <!--//コメント投稿-->
    </div>
    {% include 'base/sidebar.html' %}
</div>
{% endblock %}
{% block js %}
<script src="{% static 'js/vote.js' %}" type='text/javascript'></script>
{% endblock %}